// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntmokzjaobzkmbcidpuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50bW9remphb2J6a21iY2lkcHVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3Mzk5OTgsImV4cCI6MjA2MzMxNTk5OH0.-KFUL7rUKzf0Fidczy_5Leke5UNFBEPEdX0FRzZd9AI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);